create index IND_PRAVS on facebook (AGE,GENDER,DOB_YEAR,USERID);

SELECT COUNT(*) FROM FACEBOOK WHERE DOB_YEAR=1999;

SELECT AGE,COUNT(*)
FROM FACEBOOK 
GROUP BY AGE
ORDER BY AGE;

SELECT COUNT(USERID)
FROM FACEBOOK
WHERE AGE>15;

SELECT(SUM(CASE WHEN GENDER = 'female'
THEN 1 ELSE 0 END)  / COUNT(*)*100) AS FEMALE_PERCENTAGE
FROM FACEBOOK;

SELECT (SUM(CASE WHEN GENDER = 'female' THEN 1 end)  / count(*)*100) as FEMALE_PERCENTAGE
from FACEBOOK WHERE age>17;